{% set name = "filelock" %}
{% set version = "3.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b795f1b42a61bbf8ec7113c341dad679d772567b936fbd1bf43c9a238e673e20

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python >=3.7
    # Needed to get correct version number in the metadata.
    - setuptools_scm

  run:
    - python >=3.7

test:
  imports:
    - filelock

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Unlicense
  license_file: LICENSE
  summary: A platform independent file lock.

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
