{% set name = "filelock" %}
{% set version = "3.10.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c0312de887536b07321e16e6428a580497be288259baa501bf898e39f9486f3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.11.1
    - hatch-vcs >=0.3

  run:
    - python >=3.7

test:
  imports:
    - filelock

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Unlicense
  license_file: LICENSE
  summary: A platform independent file lock.

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
