{% set name = "filelock" %}
{% set version = "3.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9cd540a9352e432c7246a48fe4e8712b10acb1df2ad1f30e8c070b82ae1fed85

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps .

requirements:
  host:
    - pip
    - python >=3.7
    # Needed to get correct version number in the metadata.
    - setuptools_scm

  run:
    - python >=3.7

test:
  imports:
    - filelock

about:
  home: https://github.com/benediktschmitt/py-filelock
  license: Unlicense
  license_file: LICENSE
  summary: A platform independent file lock.

extra:
  recipe-maintainers:
    - jakirkham
    - mariusvniekerk
    - nicoddemus
